
### addUser
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "a3",
  "lastName": "b3"
}

### delUser
DELETE http://localhost:3000/users/4


### updateUser
PUT http://localhost:3000/users/2
Content-Type: application/json

{
  "firstName": "a2",
  "lastName": "b2"
}


### getUsers
GET http://localhost:3000/users


### getUser
GET http://localhost:3000/users/3

